### ISSUE TITLE
KDialog Has Been Ported to KF5

### ISSUE THREAD

**Issue by MichaelTunnell** [blackPantherOS/playground#1]
I am not sure when it was ported but it has been ported to KF5. I was wondering if PyDialog works independently from Qt because it would be fantastic to have an option that would run on other DEs without the need for KDE dependencies.

I really like the idea of PyDialog having the syntax of KDialog and if it were possible to use KDialog on Plasma and PyDialog on everything else then that would be fantastic because it would make it so scripts would be cross-desktop compatible.

Would this kind of thing be possible?

**Comment by blackPantherOS** [comment]
Hi, yes kdialog is ported to KF5 already. PyDialog a absolutly independed development from KDE/Plasma but this is a Qt5 based dialog. To today PyDialog use more self other switch and option, example --showsettings.
So until now we do not think of any other interface , example Gtk. 

For Gtk available the zenity, gtk-dialog, etc. Why do you think, the PyDialog is better solution on Gtk based environment?

**Comment by hmikihth** [comment]
Hi Michael! Unfortunately, I have been finished to develop GTK+ based softwares around 2010 because the multithreading was horrible in GTK+ and I didn't want to see frozen windows in our distro. It is the reason why the PyDialog is based only on Qt5.

**Comment by MichaelTunnell** [comment]
I understand your issues with GTK, I can't stand GTK anymore actually. I was just wondering how portable it is due to the Python approach. Zenity is fine for GTK I was just curious because of the shared syntax PyDialog has with KDialog.

Have you tested this in LXQt? I think it would be a good solution for that DE where as KDialog requiring extra dependencies vs PyDialog.

**Comment by blackPantherOS** [comment]
PyDialog working with any desktop environment if [PyQt5](https://pypi.python.org/pypi/PyQt5) package is installed what provides your favorite distro. Do not need installed plasma or any KDE5 components.
